# Generated by Django 5.1.7 on 2025-03-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='abhinavabhi192018@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
